server:
  port: 7979
  servlet:
    context-path: "/products"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db.migration/v2_users_table.sql
